### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by huguesalary** [concourse/registry-image-resource#50]
I am trying to setup a Concourse-CI pipeline that uses a `put` step to push a `.tar` image built on the previous step.

Unfortunately my `put` step fails with the following error.

I'm not sure whether the issue comes from this repo in `cmd/out/main.go:90 +0x733` or if it comes from the library you're using 
```
github.com/google/go-containerregistry/pkg/v1/tarball.(*image).loadTarDescriptorAndConfig(0xc000044440, 0x0, 0x0)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20181122122528-61e4aeff7593/pkg/v1/tarball/image.go:158 +0x151
```

Here's the full error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6912a1]

goroutine 1 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.(*image).loadTarDescriptorAndConfig(0xc000044440, 0x0, 0x0)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20181122122528-61e4aeff7593/pkg/v1/tarball/image.go:158 +0x151
github.com/google/go-containerregistry/pkg/v1/tarball.Image(0xc00000c600, 0x0, 0xc00000c600, 0x1, 0xc000016120, 0x22)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20181122122528-61e4aeff7593/pkg/v1/tarball/image.go:75 +0x62
github.com/google/go-containerregistry/pkg/v1/tarball.ImageFromPath(0xc000016120, 0x22, 0x0, 0xc000016120, 0x22, 0x0, 0x0)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20181122122528-61e4aeff7593/pkg/v1/tarball/image.go:66 +0x4d
main.main()
	/src/cmd/out/main.go:90 +0x733
```

**Comment by huguesalary** [comment]
The image in question was built with Kaniko (https://github.com/GoogleContainerTools/kaniko). I'll try the suggested builder (concourse/builder) and see if I'm still running into this issue.

**Comment by huguesalary** [comment]
Using the `concourse/builder` image works, so the issue must be coming from Kaniko outputting an image in a format `go-containerregistry` does not understand

**Comment by xtremerui** [comment]
Is this issue resolved now by newer versions of both kaniko and go-containerregistry
